Vagrant.configure(2) do |config|
  config.ssh.username = 'vagrant'
  #config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.ssh.forward_agent = true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "testbox"
  config.vm.network "private_network", ip: "192.168.56.22"

  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = "SF_P6_vagrant_ubuntu"
    v.memory = 2048
  end
  
 config.vm.provision "ansible" do |ansible|
     ansible.limit = "all,localhost"
     ansible.playbook = "testbox.yml"
     ansible.inventory_path = "./hosts"
 end
end